jar {
    enabled = false
}

tasks.named('bootJar') {
    layered {
        enabled = true
    }
}

dependencies {
    implementation project(':app:core')
    testImplementation testFixtures(project(':app:core'))

    implementation "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
}