plugins {
    id 'jacoco-report-aggregation'
}

repositories {
    mavenCentral()
}

dependencies {
    jacocoAggregation project(':app:core')
    jacocoAggregation project(':app:containers:api')
    jacocoAggregation project(':app:containers:scheduler')
}

reporting {
    reports {
        testCodeCoverageReport(JacocoCoverageReport) {
            testType = 'unit-test'
        }
    }
}

tasks.register('codeChecks') {
    group = 'verification'
    description = 'Runs Checkstyle and PMD for the kafka-producer project.'
}

gradle.projectsEvaluated {
    def coverageReport = tasks.named('testCodeCoverageReport')
    subprojects.each { project ->
        project.tasks.matching { it.name == 'test' }.configureEach {
            it.finalizedBy coverageReport
        }
    }
}
