org.gradle.parallel=true

testcontainersVersion=2.0.5
postgresqlVersion=42.7.3
springCloudOpenfeignVersion=4.1.3
springBootVersion=3.3.3
dependencyManagementPluginVersion=1.1.6
springCloudVersion=2023.0.3
lombokVersion=1.18.34
dataFakerVersion=2.1.0
springKafkaVersion=3.2.3
jacksonVersion=2.17.2
mapstructVersion=1.6.3
flywayVersion=11.3.1
hypersistenceUtilsVersion=3.9.1
hibernateVersion=6.6.6.Final