---
# Source: dev/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-producer-api-dev-configmap
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-producer-api
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
data:
  DATABASE_HOST: "postgresql"
  DATABASE_NAME: "kafka-producer"
  DATABASE_PASSWORD: "example"
  DATABASE_PORT: "5432"
  DATABASE_USER: "root"
  GEOCODING_URL: "https://geocoding-api.open-meteo.com"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  OPENMETEO_FORECAST_URL: "https://api.open-meteo.com/v1/forecast"
  SPRING_PROFILE: "dev"
---
# Source: dev/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-api-dev-service
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-producer-api
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-producer-api
---
# Source: dev/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-api-dev
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-producer-api
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dev
      app.kubernetes.io/instance: kafka-producer-api
  template:
    metadata:
      annotations:
        rollme: "JL0Hr"
      labels:
        helm.sh/chart: dev-0.1.0
        app.kubernetes.io/name: dev
        app.kubernetes.io/instance: kafka-producer-api
        app.kubernetes.io/version: "latest"
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: kafka-producer-api-dev
          image: "kafka-producer-api-dev:2025.06.27.01.34.14"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: kafka-producer-api-dev-configmap
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 60
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 60
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 60
          resources:
            limits:
              cpu: 400m
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 512Mi
