---
# Source: dev/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-producer-dev-configmap
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-producer
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_PROFILE: "dev"
---
# Source: dev/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-dev-service
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-producer
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-producer
---
# Source: dev/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-dev
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-producer
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dev
      app.kubernetes.io/instance: kafka-producer
  template:
    metadata:
      labels:
        helm.sh/chart: dev-0.1.0
        app.kubernetes.io/name: dev
        app.kubernetes.io/instance: kafka-producer
        app.kubernetes.io/version: "latest"
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: kafka-producer-dev
          image: "kafka-producer:latest"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: kafka-producer-dev-configmap
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 400m
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 512Mi
