apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  serviceName: zookeeper
  replicas: 1
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:latest
          ports:
            - containerPort: 2181
          envFrom:
            - configMapRef:
                name: zookeeper-configmap
          livenessProbe:
            tcpSocket:
              port: 2181
          readinessProbe:
            tcpSocket:
              port: 2181
