apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-worker-configmap
data:
  DB__HOST: postgres-service
  DB__USER: root
  DB__PASSWORD: example
  DB__NAME: kafka-worker
  KAFKA__KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
  KAFKA__KAFKA_CONSUMER_GROUP_ID: kafka-worker
  KAFKA__TOPICS__EXAMPLE_EVENTS: example-topic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-worker
spec:
  selector:
    matchLabels:
      app: kafka-worker
  template:
    metadata:
      labels:
        app: kafka-worker
    spec:
      containers:
        - name: kafka-worker
          image: worker-test:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: kafka-worker-configmap
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
