FROM python:3.11.7-alpine

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

CMD ["python", "manage.py", "start_example_events_consumer"]
