---
# Source: dev/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-worker-scheduler-dev-configmap
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-worker-scheduler
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
data:
  DATABASE_HOST: "postgresql"
  DATABASE_NAME: "kafka-worker"
  DATABASE_PASSWORD: "example"
  DATABASE_PORT: "5432"
  DATABASE_USER: "root"
---
# Source: dev/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-worker-scheduler-dev-service
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-worker-scheduler
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8006
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-worker-scheduler

---
# Source: dev/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-worker-scheduler-dev
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-worker-scheduler
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dev
      app.kubernetes.io/instance: kafka-worker-scheduler
  template:
    metadata:
      annotations:
        pipeline_deployed_at: "2026-06-06T15:34:11.279708+00:00"
        pipeline_id: 7f856905-4d6f-4be1-874a-0514c3dc33dc
      labels:
        helm.sh/chart: dev-0.1.0
        app.kubernetes.io/name: dev
        app.kubernetes.io/instance: kafka-worker-scheduler
        app.kubernetes.io/version: "latest"
        app.kubernetes.io/managed-by: Helm
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: kafka-worker-scheduler-dev
          image: "kafka-worker-scheduler-dev:dev"
          imagePullPolicy: Never
          command:
            - /docker-entrypoint.sh
          args:
            - python
            - manage.py
            - start_scheduler
          ports:
            - name: http
              containerPort: 8006
              protocol: TCP
          envFrom:
            - configMapRef:
                name: kafka-worker-scheduler-dev-configmap
          livenessProbe:
            null
          readinessProbe:
            null
          startupProbe:
            null
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
