---
# Source: dev/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-worker-api-dev-configmap
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-worker-api
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
data:
  AWS_ACCESS_KEY_ID: "test"
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_ENDPOINT_URL: "http://localstack:4566"
  AWS_SECRET_ACCESS_KEY: "test"
  DATABASE_HOST: "postgresql"
  DATABASE_NAME: "kafka-worker"
  DATABASE_PASSWORD: "example"
  DATABASE_PORT: "5432"
  DATABASE_USER: "root"
---
# Source: dev/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-worker-api-dev-service
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-worker-api
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-worker-api

---
# Source: dev/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-worker-api-dev
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-worker-api
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dev
      app.kubernetes.io/instance: kafka-worker-api
  template:
    metadata:
      annotations:
        pipeline_deployed_at: "2026-06-06T15:18:16.468613+00:00"
        pipeline_id: e45f5652-8ac3-406e-9ea9-45c494d335f5
      labels:
        helm.sh/chart: dev-0.1.0
        app.kubernetes.io/name: dev
        app.kubernetes.io/instance: kafka-worker-api
        app.kubernetes.io/version: "latest"
        app.kubernetes.io/managed-by: Helm
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: kafka-worker-api-dev
          image: "kafka-worker-api-dev:dev"
          imagePullPolicy: Never
          command:
            - python
          args:
            - -m
            - gunicorn
            - kafkaworker.asgi:application
            - -k
            - uvicorn.workers.UvicornWorker
            - -b
            - 0.0.0.0:8000
            - --graceful-timeout
            - "30"
            - --timeout
            - "60"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: kafka-worker-api-dev-configmap
          livenessProbe:
            null
          readinessProbe:
            null
          startupProbe:
            null
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
