---
# Source: dev/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-worker-api-dev-configmap
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-worker-api
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
data:
  DB__HOST: "postgresql"
  DB__NAME: "kafka-worker"
  DB__PASSWORD: "example"
  DB__USER: "root"
---
# Source: dev/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-worker-api-dev-service
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-worker-api
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-worker-api
---
# Source: dev/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-worker-api-dev
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-worker-api
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dev
      app.kubernetes.io/instance: kafka-worker-api
  template:
    metadata:
      labels:
        helm.sh/chart: dev-0.1.0
        app.kubernetes.io/name: dev
        app.kubernetes.io/instance: kafka-worker-api
        app.kubernetes.io/version: "latest"
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: kafka-worker-api-dev
          image: "kafka-worker:latest"
          imagePullPolicy: Never
          command:
            - python
          args:
            - -m
            - gunicorn
            - kafkaworker.asgi:application
            - -k
            - uvicorn.workers.UvicornWorker
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: kafka-worker-api-dev-configmap
          livenessProbe:
            null
          readinessProbe:
            null
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
