---
# Source: dev/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-worker-example-topic-consumer-dev-configmap
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-worker-example-topic-consumer
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
data:
  DATABASE_HOST: "postgresql"
  DATABASE_NAME: "kafka-worker"
  DATABASE_PASSWORD: "example"
  DATABASE_PORT: "5432"
  DATABASE_USER: "root"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_CONSUMER_GROUP_ID: "kafka-worker"
  KAFKA_TOPICS_EXAMPLE_EVENTS: "example-topic"
---
# Source: dev/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-worker-example-topic-consumer-dev-service
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-worker-example-topic-consumer
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8005
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-worker-example-topic-consumer
---
# Source: dev/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-worker-example-topic-consumer-dev
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: kafka-worker-example-topic-consumer
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dev
      app.kubernetes.io/instance: kafka-worker-example-topic-consumer
  template:
    metadata:
      annotations:
        rollme: "17Lzq"
      labels:
        helm.sh/chart: dev-0.1.0
        app.kubernetes.io/name: dev
        app.kubernetes.io/instance: kafka-worker-example-topic-consumer
        app.kubernetes.io/version: "latest"
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: kafka-worker-example-topic-consumer-dev
          image: "kafka-worker-example-topic-consumer-dev:2025.03.12.01.01.54"
          imagePullPolicy: Never
          command:
            - python
          args:
            - manage.py
            - start_example_events_consumer
          ports:
            - name: http
              containerPort: 8005
              protocol: TCP
          envFrom:
            - configMapRef:
                name: kafka-worker-example-topic-consumer-dev-configmap
          livenessProbe:
            exec:
              command:
              - ./worker_health_check.py
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 60
          readinessProbe:
            exec:
              command:
              - ./worker_health_check.py
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 60
          startupProbe:
            exec:
              command:
              - ./worker_health_check.py
            failureThreshold: 30
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 60
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
