.PHONY: create-env, install-requirements

create-env:
	@echo "Creating virtual environment..."
	@python3 -m venv .venv
	@echo "Virtual environment created."

install-requirements:
	@echo "Installing requirements..."
	@pip3 install -r requirements.txt
	@echo "Requirements installed."
