resources:
  limits:
    cpu: 250m
    memory: 512Mi

  requests:
    cpu: 150m
    memory: 256Mi

autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 2
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
