spring.profiles.active: local

spring.http.gateways:
    geocoding.url: ${GEOCODING_URL}
    openmeteo.forecast.url: ${OPENMETEO_FORECAST_URL}

server:
    address: 0.0.0.0
    port: 8080
    shutdown: graceful

management:
    endpoints.web.exposure.include: ["health", "info", "prometheus"]
    endpoint.health.probes.enabled: true
    health:
        livenessState.enabled: true
        readinessState.enabled: true

spring.datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
