spring.kafka.bootstrap-servers: kafka:9092

spring.datasource:
    url: "jdbc:postgresql://postgres:5432/kafka-producer"
    username: ysdcr
    password: ysdcr

spring.http.gateways:
    geocoding.url: http://geocoding-api
    openmeteo.forecast.url: http://open-meteo-forecast-api
