apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-configmap
data:
  KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper-service:2181"
  ALLOW_PLAINTEXT_LISTENER: "yes"
  KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
  KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service:9092"