apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: producer-test:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: kafka-producer-configmap
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
