resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

yamlApplicationConfig:
  kafka:
    clusters:
      - name: local
        bootstrapServers: kafka:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false
