DATABASE_HOST: localhost
DATABASE_USER: ysdcr
DATABASE_PASSWORD: ysdcr
DATABASE_NAME: kafka-worker

KAFKA_BOOTSTRAP_SERVERS: localhost:9092
KAFKA_CONSUMER_GROUP_ID: kafka-worker
KAFKA_TOPICS_EXAMPLE_EVENTS: local-example-events

AWS_ENDPOINT_URL: http://localhost:4566