DB:
  HOST: localhost
  USER: postgres
  PASSWORD: postgres
  NAME: kafka-worker
KAFKA:
  KAFKA_BOOTSTRAP_SERVERS: localhost:9092
  KAFKA_CONSUMER_GROUP_ID: kafka-worker
  TOPICS:
    EXAMPLE_EVENTS: local-example-events
