apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-admin
spec:
  selector:
    matchLabels:
      app: kafka-admin
  template:
    metadata:
      labels:
        app: kafka-admin
    spec:
      containers:
        - name: kafka-admin
          image: provectuslabs/kafka-ui:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: kafka-admin-configmap
          ports:
            - containerPort: 8080
              protocol: TCP
