apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka
  replicas: 1
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
          envFrom:
            - configMapRef:
                name: kafka-configmap
          livenessProbe:
            tcpSocket:
              port: 9092
          readinessProbe:
            tcpSocket:
              port: 9092
