spring:   
    kafka.bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    http.gateways:
        geocoding.url: https://geocoding-api.open-meteo.com
        openmeteo.forecast.url: https://api.open-meteo.com/v1/forecast

server:
    shutdown: graceful
    port: 8080

logging:
    level:
        # root: DEBUG
        com.github.yuriserka.kafkaproducer: DEBUG
