apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-worker
spec:
  selector:
    matchLabels:
      app: kafka-worker
  template:
    metadata:
      labels:
        app: kafka-worker
    spec:
      containers:
        - name: kafka-worker
          image: worker-test:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: kafka-worker-configmap
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
