apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-configmap
data:
  KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper-service:2181"
  ALLOW_PLAINTEXT_LISTENER: "yes"
  KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
  KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service:9092"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - name: port
      port: 9092
      targetPort: 9092
      protocol: TCP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka
  replicas: 1
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
          envFrom:
            - configMapRef:
                name: kafka-configmap
          livenessProbe:
            tcpSocket:
              port: 9092
          readinessProbe:
            tcpSocket:
              port: 9092
